# Configuración para usar la base de datos en memoria (H2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto evita que Spring falle si no encuentra tablas creadas
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true