spring.application.name=demo

# Configuración de Base de Datos H2 (Archivo local - Persistente)
spring.datasource.url=jdbc:h2:./data/logistica_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola H2 y actualizar tablas
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Forzar el puerto 8080
server.port=8080

# Configuración de SpringDoc OpenAPI (Swagger UI)
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Desabilitar advertencia JPA open-in-view
spring.jpa.open-in-view=false